sudo: required
language: Java
notifications:
  email: nehal.borole@gmail.com
services:
  - docker
jdk:
  - openjdk8

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"
before_deploy:
  - git config --local user.name "Nehal Borole"
  - git config --local user.email "nehal.borole@gmail.com"
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
  - "./gradlew releaseZip"
deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: "./build/libs/Algocup-Judge-*.zip"
    skip_cleanup: true
    on:
      tags: false