logging:
  path: ./logs

server:
  port: ${PORT:5008}

jalgoarena:
  problems:
    source: ${PROBLEMS_SOURCE:problems.json}
  judge:
    classpath: ${JUDGE_CLASSPATH:build/classes/kotlin/main}

spring:
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS:localhost:8808}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID:judge-agent}
    producer:
      retries: 3
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  jackson:
    deserialization:
      ADJUST_DATES_TO_CONTEXT_TIME_ZONE: false
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false